@echo off
setlocal EnableDelayedExpansion
title File Auto-Renamer - by Biraj2004
cd /d "%~dp0"

:: =========================================================================================================
:: GitHub      : https://github.com/Biraj2004
:: Developer   : Biraj
:: Description : Recursively scans this folder and ALL subfolders for
::                .mp4, .mkv, and .pdf files, sorts them by earliest
::                Downloaded/Created time (CreationTime), ascending, and
::                prefixes each filename with a sequential number
::                ("01 - ", "02 - ", ...).
::                - EACH FOLDER (this folder + every subfolder) is numbered
::                  INDEPENDENTLY, starting fresh at 01 (or 001... if that
::                  specific folder has 100+ matching files).
::                - If a folder has less than 100 matched files -> 2-digit (01, 02 ...)
::                - If a folder has 100 or more matched files   -> auto-expands digits (001, 0001 ...)
::                - Original filename text is NEVER modified, only prefixed.
::                - Re-running this script is SAFE: any old "NN - " prefix is
::                  stripped first, then files are freshly re-numbered.
:: =========================================================================================================

echo =======================================================================================================
echo                       FILE AUTO-NUMBERING SCRIPT
echo                       Developed by : Biraj
echo                       GitHub       : https://github.com/Biraj2004
echo =======================================================================================================
echo.
echo [INFO] Working Folder   : %CD%
echo [INFO] Target Extensions: .mp4, .mkv, .webm, .pdf
echo [INFO] Sorting Rule     : Earliest Downloaded/Created Time (CreationTime), Ascending
echo [INFO] Numbering Format : 2-digit (01 - ) if a folder has less than 100 files
echo [INFO]                    3+ digit (001 - / 0001 - ...) if that folder has 100 or more files
echo [INFO] Scope            : Current folder + ALL subfolders (Recursive)
echo [INFO] Numbering Rule   : Each folder gets its OWN independent numbering, restarting at 01
echo [INFO] Safety           : Only the numbered-prefix is added/replaced. Titles are untouched.
echo.
echo =======================================================================================================
echo  WARNING: This will RENAME .mp4, .mkv, .webm, and .pdf files inside:
echo    %CD%
echo  ...and every SUB-FOLDER inside it.
echo =======================================================================================================
echo.
set "CONFIRM="
set /p CONFIRM=Type Y and press Enter to proceed, or N to cancel : 

if /i "%CONFIRM%"=="Y" goto :PROCEED
if /i "%CONFIRM%"=="YES" goto :PROCEED

echo.
echo [CANCELLED] No files were scanned or renamed. Exiting safely.
echo.
pause
endlocal
exit /b 0

:PROCEED
echo.
echo [PROCESSING] Launching PowerShell engine...
echo =======================================================================================================

where powershell >nul 2>&1
if errorlevel 1 (
    echo [ERROR] PowerShell was not found on this system. Cannot continue.
    echo.
    pause
    exit /b 1
)

powershell -NoProfile -NoLogo -ExecutionPolicy Bypass -EncodedCommand "JABFAHIAcgBvAHIAQQBjAHQAaQBvAG4AUAByAGUAZgBlAHIAZQBuAGMAZQAgAD0AIAAnAFMAdABvAHAAJwAKACQAZQB4AHQAcwAgAD0AIABAACgAJwAuAG0AcAA0ACcALAAnAC4AbQBrAHYAJwAsACcALgBwAGQAZgAnACkACgAkAHIAbwBvAHQAIAA9ACAARwBlAHQALQBMAG8AYwBhAHQAaQBvAG4ACgBXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgBbAEkATgBGAE8AXQAgAFMAYwBhAG4AbgBpAG4AZwAgAGYAbwBsAGQAZQByACAAKAByAGUAYwB1AHIAcwBpAHYAZQApADoAIAAkAHIAbwBvAHQAIgAgAC0ARgBvAHIAZQBnAHIAbwB1AG4AZABDAG8AbABvAHIAIABHAHIAYQB5AAoAJABmAGkAbABlAHMAIAA9ACAARwBlAHQALQBDAGgAaQBsAGQASQB0AGUAbQAgAC0AUABhAHQAaAAgACQAcgBvAG8AdAAgAC0AUgBlAGMAdQByAHMAZQAgAC0ARgBpAGwAZQAgAHwAIABXAGgAZQByAGUALQBPAGIAagBlAGMAdAAgAHsAIAAkAGUAeAB0AHMAIAAtAGMAbwBuAHQAYQBpAG4AcwAgACQAXwAuAEUAeAB0AGUAbgBzAGkAbwBuAC4AVABvAEwAbwB3AGUAcgAoACkAIAB9AAoAJAB0AG8AdABhAGwAIAA9ACAAJABmAGkAbABlAHMALgBDAG8AdQBuAHQACgBpAGYAIAAoACQAdABvAHQAYQBsACAALQBlAHEAIAAwACkAIAB7AAoAIAAgACAAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgBbAEkATgBGAE8AXQAgAE4AbwAgAG0AYQB0AGMAaABpAG4AZwAgAGYAaQBsAGUAcwAgACgALgBtAHAANAAsACAALgBtAGsAdgAsACAALgBwAGQAZgApACAAZgBvAHUAbgBkAC4AIgAgAC0ARgBvAHIAZQBnAHIAbwB1AG4AZABDAG8AbABvAHIAIABZAGUAbABsAG8AdwAKACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAgACIAIgAKACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAgACIAUAByAGUAcwBzACAAYQBuAHkAIABrAGUAeQAgAHQAbwAgAGUAeABpAHQALgAuAC4AIgAKACAAIAAgACAAWwB2AG8AaQBkAF0AWwBTAHkAcwB0AGUAbQAuAEMAbwBuAHMAbwBsAGUAXQA6ADoAUgBlAGEAZABLAGUAeQAoACQAdAByAHUAZQApAAoAIAAgACAAIABlAHgAaQB0AAoAfQAKACQAZwByAG8AdQBwAHMAIAA9ACAAJABmAGkAbABlAHMAIAB8ACAARwByAG8AdQBwAC0ATwBiAGoAZQBjAHQAIABEAGkAcgBlAGMAdABvAHIAeQBOAGEAbQBlACAAfAAgAFMAbwByAHQALQBPAGIAagBlAGMAdAAgAE4AYQBtAGUACgBXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgBbAEkATgBGAE8AXQAgAEYAbwB1AG4AZAAgACQAdABvAHQAYQBsACAAbQBhAHQAYwBoAGkAbgBnACAAZgBpAGwAZQAoAHMAKQAgAGEAYwByAG8AcwBzACAAJAAoACQAZwByAG8AdQBwAHMALgBDAG8AdQBuAHQAKQAgAGYAbwBsAGQAZQByACgAcwApAC4AIgAgAC0ARgBvAHIAZQBnAHIAbwB1AG4AZABDAG8AbABvAHIAIABHAHIAYQB5AAoAVwByAGkAdABlAC0ASABvAHMAdAAgACIAWwBJAE4ARgBPAF0AIABFAGEAYwBoACAAZgBvAGwAZABlAHIAIABpAHMAIABuAHUAbQBiAGUAcgBlAGQAIABpAG4AZABlAHAAZQBuAGQAZQBuAHQAbAB5ACwAIABzAHQAYQByAHQAaQBuAGcAIABmAHIAZQBzAGgAIABhAHQAIAAwADEAIAAoAG8AcgAgADAAMAAxAC4ALgAuACkALgAiACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAEcAcgBhAHkACgBXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgAiAAoAJABnAHIAYQBuAGQAUgBlAG4AYQBtAGUAZAAgAD0AIAAwAAoAJABnAHIAYQBuAGQAUwBrAGkAcABwAGUAZAAgAD0AIAAwAAoAJABnAHIAYQBuAGQARQByAHIAbwByAHMAIAA9ACAAMAAKAGYAbwByAGUAYQBjAGgAIAAoACQAZwByAG8AdQBwACAAaQBuACAAJABnAHIAbwB1AHAAcwApACAAewAKACAAIAAgACAAJABmAG8AbABkAGUAcgBGAGkAbABlAHMAIAA9ACAAJABnAHIAbwB1AHAALgBHAHIAbwB1AHAAIAB8ACAAUwBvAHIAdAAtAE8AYgBqAGUAYwB0ACAAQwByAGUAYQB0AGkAbwBuAFQAaQBtAGUACgAgACAAIAAgACQAZgBvAGwAZABlAHIAVABvAHQAYQBsACAAPQAgACQAZgBvAGwAZABlAHIARgBpAGwAZQBzAC4AQwBvAHUAbgB0AAoAIAAgACAAIABpAGYAIAAoACQAZgBvAGwAZABlAHIAVABvAHQAYQBsACAALQBsAHQAIAAxADAAMAApACAAewAgACQAZABpAGcAaQB0AHMAIAA9ACAAMgAgAH0AIABlAGwAcwBlACAAewAgACQAZABpAGcAaQB0AHMAIAA9ACAAKAAkAGYAbwBsAGQAZQByAFQAbwB0AGEAbAAuAFQAbwBTAHQAcgBpAG4AZwAoACkALgBMAGUAbgBnAHQAaAApACAAfQAKACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAgACIALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAiAAoAIAAgACAAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgBbAEYATwBMAEQARQBSAF0AIAAgACQAKAAkAGcAcgBvAHUAcAAuAE4AYQBtAGUAKQAiACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAE0AYQBnAGUAbgB0AGEACgAgACAAIAAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiACAAIAAgACAAIAAgACAAIAAgACAAJABmAG8AbABkAGUAcgBUAG8AdABhAGwAIABmAGkAbABlACgAcwApACAALQAtACAAdQBzAGkAbgBnACAAJABkAGkAZwBpAHQAcwAtAGQAaQBnAGkAdAAgAG4AdQBtAGIAZQByAGkAbgBnACIAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAARABhAHIAawBNAGEAZwBlAG4AdABhAAoAIAAgACAAIAAkAGMAbwB1AG4AdAAgAD0AIAAxAAoAIAAgACAAIABmAG8AcgBlAGEAYwBoACAAKAAkAGYAaQBsAGUAIABpAG4AIAAkAGYAbwBsAGQAZQByAEYAaQBsAGUAcwApACAAewAKACAAIAAgACAAIAAgACAAIAAkAHAAcgBlAGYAaQB4ACAAPQAgACQAYwBvAHUAbgB0AC4AVABvAFMAdAByAGkAbgBnACgAKQAuAFAAYQBkAEwAZQBmAHQAKAAkAGQAaQBnAGkAdABzACwAJwAwACcAKQAKACAAIAAgACAAIAAgACAAIAAkAGMAbABlAGEAbgBOAGEAbQBlACAAPQAgACQAZgBpAGwAZQAuAE4AYQBtAGUAIAAtAHIAZQBwAGwAYQBjAGUAIAAnAF4AXABkAHsAMgAsAH0AXABzACoALQBcAHMAKgAnACwAJwAnAAoAIAAgACAAIAAgACAAIAAgACQAbgBlAHcATgBhAG0AZQAgAD0AIAAiACQAcAByAGUAZgBpAHgAIAAtACAAJABjAGwAZQBhAG4ATgBhAG0AZQAiAAoAIAAgACAAIAAgACAAIAAgAGkAZgAgACgAJABmAGkAbABlAC4ATgBhAG0AZQAgAC0AZQBxACAAJABuAGUAdwBOAGEAbQBlACkAIAB7AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAgACIAWwBTAEsASQBQAF0AIAAgACAAIAAgACQAKAAkAGYAaQBsAGUALgBOAGEAbQBlACkAIAAgACgAYQBsAHIAZQBhAGQAeQAgAG4AdQBtAGIAZQByAGUAZAAgAGMAbwByAHIAZQBjAHQAbAB5ACkAIgAgAC0ARgBvAHIAZQBnAHIAbwB1AG4AZABDAG8AbABvAHIAIABEAGEAcgBrAEcAcgBhAHkACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAGcAcgBhAG4AZABTAGsAaQBwAHAAZQBkACsAKwAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAYwBvAHUAbgB0ACsAKwAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGMAbwBuAHQAaQBuAHUAZQAKACAAIAAgACAAIAAgACAAIAB9AAoAIAAgACAAIAAgACAAIAAgAHQAcgB5ACAAewAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAFIAZQBuAGEAbQBlAC0ASQB0AGUAbQAgAC0ATABpAHQAZQByAGEAbABQAGEAdABoACAAJABmAGkAbABlAC4ARgB1AGwAbABOAGEAbQBlACAALQBOAGUAdwBOAGEAbQBlACAAJABuAGUAdwBOAGEAbQBlACAALQBFAHIAcgBvAHIAQQBjAHQAaQBvAG4AIABTAHQAbwBwAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAgACIAWwBSAEUATgBBAE0ARQBEAF0AIAAgACQAKAAkAGYAaQBsAGUALgBOAGEAbQBlACkAIgAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiACAAIAAgACAAIAAtAC0APgAgACAAIAAkAG4AZQB3AE4AYQBtAGUAIgAgAC0ARgBvAHIAZQBnAHIAbwB1AG4AZABDAG8AbABvAHIAIABDAHkAYQBuAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABnAHIAYQBuAGQAUgBlAG4AYQBtAGUAZAArACsACgAgACAAIAAgACAAIAAgACAAfQAgAGMAYQB0AGMAaAAgAHsACgAgACAAIAAgACAAIAAgACAAIAAgACAAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgBbAEUAUgBSAE8AUgBdACAAIAAgACAAQwBvAHUAbABkACAAbgBvAHQAIAByAGUAbgBhAG0AZQAgACQAKAAkAGYAaQBsAGUALgBGAHUAbABsAE4AYQBtAGUAKQAgAC0ALQAgACQAKAAkAF8ALgBFAHgAYwBlAHAAdABpAG8AbgAuAE0AZQBzAHMAYQBnAGUAKQAiACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAFIAZQBkAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABnAHIAYQBuAGQARQByAHIAbwByAHMAKwArAAoAIAAgACAAIAAgACAAIAAgAH0ACgAgACAAIAAgACAAIAAgACAAJABjAG8AdQBuAHQAKwArAAoAIAAgACAAIAB9AAoAfQAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiACIACgBXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtACIACgBXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgBbAFMAVQBNAE0AQQBSAFkAXQAgAFQAbwB0AGEAbAAgAG0AYQB0AGMAaABlAGQAIAA6ACAAJAB0AG8AdABhAGwAIgAgAC0ARgBvAHIAZQBnAHIAbwB1AG4AZABDAG8AbABvAHIAIABHAHIAZQBlAG4ACgBXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgBbAFMAVQBNAE0AQQBSAFkAXQAgAEYAbwBsAGQAZQByAHMAIAAgACAAIAAgACAAIAA6ACAAJAAoACQAZwByAG8AdQBwAHMALgBDAG8AdQBuAHQAKQAiACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAEcAcgBlAGUAbgAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAFsAUwBVAE0ATQBBAFIAWQBdACAAUgBlAG4AYQBtAGUAZAAgACAAIAAgACAAIAAgADoAIAAkAGcAcgBhAG4AZABSAGUAbgBhAG0AZQBkACIAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAARwByAGUAZQBuAAoAVwByAGkAdABlAC0ASABvAHMAdAAgACIAWwBTAFUATQBNAEEAUgBZAF0AIABTAGsAaQBwAHAAZQBkACAAIAAgACAAIAAgACAAOgAgACQAZwByAGEAbgBkAFMAawBpAHAAcABlAGQAIgAgAC0ARgBvAHIAZQBnAHIAbwB1AG4AZABDAG8AbABvAHIAIABHAHIAZQBlAG4ACgBXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgBbAFMAVQBNAE0AQQBSAFkAXQAgAEUAcgByAG8AcgBzACAAIAAgACAAIAAgACAAIAA6ACAAJABnAHIAYQBuAGQARQByAHIAbwByAHMAIgAgAC0ARgBvAHIAZQBnAHIAbwB1AG4AZABDAG8AbABvAHIAIABHAHIAZQBlAG4ACgBXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgBbAFMAVQBDAEMARQBTAFMAXQAgAE4AdQBtAGIAZQByAGkAbgBnACAAdABhAHMAawAgAGMAbwBtAHAAbABlAHQAZQAhACIAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAARwByAGUAZQBuAAoAVwByAGkAdABlAC0ASABvAHMAdAAgACIAIgAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAFAAcgBlAHMAcwAgAGEAbgB5ACAAawBlAHkAIAB0AG8AIABlAHgAaQB0AC4ALgAuACIACgBbAHYAbwBpAGQAXQBbAFMAeQBzAHQAZQBtAC4AQwBvAG4AcwBvAGwAZQBdADoAOgBSAGUAYQBkAEsAZQB5ACgAJAB0AHIAdQBlACkACgA="

echo ----------------------------------------------------------------------------
echo =======================================================================================================
echo [FINISHED] Script execution finished. GitHub: https://github.com/Biraj2004
echo =======================================================================================================
echo.
pause
endlocal