@echo off
setlocal EnableDelayedExpansion
title File Auto-Renamer - by Biraj2004
cd /d "%~dp0"

:: =======================================================================================================
:: GitHub      : https://github.com/Biraj2004
:: Developer   : Biraj
:: Description : Recursively scans this folder and ALL subfolders for
::                .mp4, .mkv, .webm, and .pdf files, sorts them by earliest
::                Downloaded/Created/Modified time (EarliestTime), ascending,
::                and prefixes each filename with a sequential number
::                ("01 - ", "02 - ", ...).
::                - Video files (.mp4, .mkv, .webm) and PDF files (.pdf) are
::                  numbered INDEPENDENTLY within each folder, each starting
::                  fresh at 01 (or 001... if that category has 100+ files).
::                - EACH FOLDER (this folder + every subfolder) is numbered
::                  independently.
::                - If a category in a folder has less than 100 files -> 2-digit (01, 02 ...)
::                - If a category in a folder has 100 or more files   -> auto-expands digits (001, 0001 ...)
::                - Original filename text is NEVER modified, only prefixed.
::                - Re-running this script is SAFE: any old "NN - " prefix is
::                  stripped first, then files are freshly re-numbered.
:: =======================================================================================================

echo =======================================================================================================
echo                       FILE AUTO-NUMBERING SCRIPT
echo                       Developed by : Biraj
echo                       GitHub       : https://github.com/Biraj2004
echo =======================================================================================================
echo.
echo [INFO] Working Folder   : %CD%
echo [INFO] Target Extensions: .mp4, .mkv, .webm, .pdf
echo [INFO] Sorting Rule     : Earliest Downloaded/Created/Modified Time, Ascending
echo [INFO] Numbering Format : 2-digit (01 - ) if a category has less than 100 files
echo [INFO]                    3+ digit (001 - / 0001 - ...) if that category has 100 or more files
echo [INFO] Scope            : Current folder + ALL subfolders (Recursive)
echo [INFO] Numbering Rule   : Video files (.mp4, .mkv, .webm) and PDF files (.pdf) are numbered
echo [INFO]                    INDEPENDENTLY in each folder, starting fresh at 01 for each type
echo [INFO] Safety           : Only the numbered-prefix is added/replaced. Titles are untouched.
echo.
echo =======================================================================================================
echo  WARNING: This will RENAME .mp4, .mkv, .webm, and .pdf files inside:
echo    %CD%
echo  ...and every SUB-FOLDER inside it.
echo =======================================================================================================
echo.
set "CONFIRM="
set /p CONFIRM=Type Y and press Enter to proceed, or N to cancel : 

if /i "%CONFIRM%"=="Y" goto :PROCEED
if /i "%CONFIRM%"=="YES" goto :PROCEED

echo.
echo [CANCELLED] No files were scanned or renamed. Exiting safely.
echo.
pause
endlocal
exit /b 0

:PROCEED
echo.
echo [PROCESSING] Launching PowerShell engine...
echo =======================================================================================================

where powershell >nul 2>&1
if errorlevel 1 (
    echo [ERROR] PowerShell was not found on this system. Cannot continue.
    echo.
    pause
    exit /b 1
)

powershell -NoProfile -NoLogo -ExecutionPolicy Bypass -EncodedCommand "JABFAHIAcgBvAHIAQQBjAHQAaQBvAG4AUAByAGUAZgBlAHIAZQBuAGMAZQAgAD0AIAAnAFMAdABvAHAAJwAKACQAdgBpAGQAZQBvAEUAeAB0AHMAIAA9ACAAQAAoACcALgBtAHAANAAnACwAJwAuAG0AawB2ACcALAAnAC4AdwBlAGIAbQAnACkACgAkAHAAZABmAEUAeAB0AHMAIAAgACAAPQAgAEAAKAAnAC4AcABkAGYAJwApAAoAJABhAGwAbABFAHgAdABzACAAIAAgAD0AIAAkAHYAaQBkAGUAbwBFAHgAdABzACAAKwAgACQAcABkAGYARQB4AHQAcwAKAAoAJAByAG8AbwB0ACAAPQAgAEcAZQB0AC0ATABvAGMAYQB0AGkAbwBuAAoAVwByAGkAdABlAC0ASABvAHMAdAAgACIAWwBJAE4ARgBPAF0AIABTAGMAYQBuAG4AaQBuAGcAIABmAG8AbABkAGUAcgAgACgAcgBlAGMAdQByAHMAaQB2AGUAKQA6ACAAJAByAG8AbwB0ACIAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAARwByAGEAeQAKACQAZgBpAGwAZQBzACAAPQAgAEcAZQB0AC0AQwBoAGkAbABkAEkAdABlAG0AIAAtAFAAYQB0AGgAIAAkAHIAbwBvAHQAIAAtAFIAZQBjAHUAcgBzAGUAIAAtAEYAaQBsAGUAIAB8ACAAVwBoAGUAcgBlAC0ATwBiAGoAZQBjAHQAIAB7ACAAJABhAGwAbABFAHgAdABzACAALQBjAG8AbgB0AGEAaQBuAHMAIAAkAF8ALgBFAHgAdABlAG4AcwBpAG8AbgAuAFQAbwBMAG8AdwBlAHIAKAApACAAfQAKACQAdABvAHQAYQBsACAAPQAgACQAZgBpAGwAZQBzAC4AQwBvAHUAbgB0AAoAaQBmACAAKAAkAHQAbwB0AGEAbAAgAC0AZQBxACAAMAApACAAewAKACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAgACIAWwBJAE4ARgBPAF0AIABOAG8AIABtAGEAdABjAGgAaQBuAGcAIABmAGkAbABlAHMAIAAoAC4AbQBwADQALAAgAC4AbQBrAHYALAAgAC4AcABkAGYAKQAgAGYAbwB1AG4AZAAuACIAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAAWQBlAGwAbABvAHcACgAgACAAIAAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiACIACgAgACAAIAAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAFAAcgBlAHMAcwAgAGEAbgB5ACAAawBlAHkAIAB0AG8AIABlAHgAaQB0AC4ALgAuACIACgAgACAAIAAgAFsAdgBvAGkAZABdAFsAUwB5AHMAdABlAG0ALgBDAG8AbgBzAG8AbABlAF0AOgA6AFIAZQBhAGQASwBlAHkAKAAkAHQAcgB1AGUAKQAKACAAIAAgACAAZQB4AGkAdAAKAH0ACgAKACQAZgBpAGwAZQBzAFcAaQB0AGgAVABpAG0AZQAgAD0AIAAkAGYAaQBsAGUAcwAgAHwAIABGAG8AcgBFAGEAYwBoAC0ATwBiAGoAZQBjAHQAIAB7AAoAIAAgACAAIAAkAGUAVABpAG0AZQAgAD0AIABpAGYAIAAoACQAXwAuAEMAcgBlAGEAdABpAG8AbgBUAGkAbQBlACAALQBsAHQAIAAkAF8ALgBMAGEAcwB0AFcAcgBpAHQAZQBUAGkAbQBlACkAIAB7ACAAJABfAC4AQwByAGUAYQB0AGkAbwBuAFQAaQBtAGUAIAB9ACAAZQBsAHMAZQAgAHsAIAAkAF8ALgBMAGEAcwB0AFcAcgBpAHQAZQBUAGkAbQBlACAAfQAKACAAIAAgACAAJABfACAAfAAgAEEAZABkAC0ATQBlAG0AYgBlAHIAIAAtAE4AbwB0AGUAUAByAG8AcABlAHIAdAB5AE4AYQBtAGUAIABFAGEAcgBsAGkAZQBzAHQAVABpAG0AZQAgAC0ATgBvAHQAZQBQAHIAbwBwAGUAcgB0AHkAVgBhAGwAdQBlACAAJABlAFQAaQBtAGUAIAAtAFAAYQBzAHMAVABoAHIAdQAgAC0ARgBvAHIAYwBlAAoAfQAKAAoAJABnAHIAbwB1AHAAcwAgAD0AIAAkAGYAaQBsAGUAcwBXAGkAdABoAFQAaQBtAGUAIAB8ACAARwByAG8AdQBwAC0ATwBiAGoAZQBjAHQAIABEAGkAcgBlAGMAdABvAHIAeQBOAGEAbQBlACAAfAAgAFMAbwByAHQALQBPAGIAagBlAGMAdAAgAE4AYQBtAGUACgBXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgBbAEkATgBGAE8AXQAgAEYAbwB1AG4AZAAgACQAdABvAHQAYQBsACAAbQBhAHQAYwBoAGkAbgBnACAAZgBpAGwAZQAoAHMAKQAgAGEAYwByAG8AcwBzACAAJAAoACQAZwByAG8AdQBwAHMALgBDAG8AdQBuAHQAKQAgAGYAbwBsAGQAZQByACgAcwApAC4AIgAgAC0ARgBvAHIAZQBnAHIAbwB1AG4AZABDAG8AbABvAHIAIABHAHIAYQB5AAoAVwByAGkAdABlAC0ASABvAHMAdAAgACIAWwBJAE4ARgBPAF0AIABWAGkAZABlAG8AcwAgACgALgBtAHAANAAsACAALgBtAGsAdgAsACAALgB3AGUAYgBtACkAIABhAG4AZAAgAFAARABGAHMAIAAoAC4AcABkAGYAKQAgAGEAcgBlACAAbgB1AG0AYgBlAHIAZQBkACAAaQBuAGQAZQBwAGUAbgBkAGUAbgB0AGwAeQAgAGkAbgAgAGUAYQBjAGgAIABmAG8AbABkAGUAcgAsACAAcwBvAHIAdABlAGQAIABiAHkAIABlAGEAcgBsAGkAZQBzAHQAIABEAG8AdwBuAGwAbwBhAGQAZQBkAC8AQwByAGUAYQB0AGUAZAAvAE0AbwBkAGkAZgBpAGUAZAAgAHQAaQBtAGUALgAiACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAEcAcgBhAHkACgBXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgAiAAoACgAkAHMAYwByAGkAcAB0ADoAZwByAGEAbgBkAFIAZQBuAGEAbQBlAGQAIAA9ACAAMAAKACQAcwBjAHIAaQBwAHQAOgBnAHIAYQBuAGQAUwBrAGkAcABwAGUAZAAgAD0AIAAwAAoAJABzAGMAcgBpAHAAdAA6AGcAcgBhAG4AZABFAHIAcgBvAHIAcwAgACAAPQAgADAACgAKACQAcAByAG8AYwBlAHMAcwBGAGkAbABlAHMAIAA9ACAAewAKACAAIAAgACAAcABhAHIAYQBtACgAJABmAGkAbABlAEwAaQBzAHQALAAgACQAZABpAGcAaQB0AHMAKQAKACAAIAAgACAAJABjAG8AdQBuAHQAIAA9ACAAMQAKACAAIAAgACAAZgBvAHIAZQBhAGMAaAAgACgAJABmAGkAbABlACAAaQBuACAAJABmAGkAbABlAEwAaQBzAHQAKQAgAHsACgAgACAAIAAgACAAIAAgACAAJABwAHIAZQBmAGkAeAAgAD0AIAAkAGMAbwB1AG4AdAAuAFQAbwBTAHQAcgBpAG4AZwAoACkALgBQAGEAZABMAGUAZgB0ACgAJABkAGkAZwBpAHQAcwAsACAAJwAwACcAKQAKACAAIAAgACAAIAAgACAAIAAkAGMAbABlAGEAbgBOAGEAbQBlACAAPQAgACQAZgBpAGwAZQAuAE4AYQBtAGUAIAAtAHIAZQBwAGwAYQBjAGUAIAAnAF4AXABkAHsAMgAsAH0AXABzACoALQBcAHMAKgAnACwAIAAnACcACgAgACAAIAAgACAAIAAgACAAJABuAGUAdwBOAGEAbQBlACAAPQAgACIAJABwAHIAZQBmAGkAeAAgAC0AIAAkAGMAbABlAGEAbgBOAGEAbQBlACIACgAKACAAIAAgACAAIAAgACAAIABpAGYAIAAoACQAZgBpAGwAZQAuAE4AYQBtAGUAIAAtAGUAcQAgACQAbgBlAHcATgBhAG0AZQApACAAewAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAFsAUwBLAEkAUABdACAAIAAgACAAIAAkACgAJABmAGkAbABlAC4ATgBhAG0AZQApACAAIAAoAGEAbAByAGUAYQBkAHkAIABuAHUAbQBiAGUAcgBlAGQAIABjAG8AcgByAGUAYwB0AGwAeQApACIAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAARABhAHIAawBHAHIAYQB5AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABzAGMAcgBpAHAAdAA6AGcAcgBhAG4AZABTAGsAaQBwAHAAZQBkACsAKwAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAYwBvAHUAbgB0ACsAKwAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGMAbwBuAHQAaQBuAHUAZQAKACAAIAAgACAAIAAgACAAIAB9AAoACgAgACAAIAAgACAAIAAgACAAdAByAHkAIAB7AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAUgBlAG4AYQBtAGUALQBJAHQAZQBtACAALQBMAGkAdABlAHIAYQBsAFAAYQB0AGgAIAAkAGYAaQBsAGUALgBGAHUAbABsAE4AYQBtAGUAIAAtAE4AZQB3AE4AYQBtAGUAIAAkAG4AZQB3AE4AYQBtAGUAIAAtAEUAcgByAG8AcgBBAGMAdABpAG8AbgAgAFMAdABvAHAACgAgACAAIAAgACAAIAAgACAAIAAgACAAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgBbAFIARQBOAEEATQBFAEQAXQAgACAAJAAoACQAZgBpAGwAZQAuAE4AYQBtAGUAKQAiAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAgACIAIAAgACAAIAAgAC0ALQA+ACAAIAAgACQAbgBlAHcATgBhAG0AZQAiACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAEMAeQBhAG4ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAHMAYwByAGkAcAB0ADoAZwByAGEAbgBkAFIAZQBuAGEAbQBlAGQAKwArAAoAIAAgACAAIAAgACAAIAAgAH0AIABjAGEAdABjAGgAIAB7AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAgACIAWwBFAFIAUgBPAFIAXQAgACAAIAAgAEMAbwB1AGwAZAAgAG4AbwB0ACAAcgBlAG4AYQBtAGUAIAAkACgAJABmAGkAbABlAC4ARgB1AGwAbABOAGEAbQBlACkAIAAtAC0AIAAkACgAJABfAC4ARQB4AGMAZQBwAHQAaQBvAG4ALgBNAGUAcwBzAGEAZwBlACkAIgAgAC0ARgBvAHIAZQBnAHIAbwB1AG4AZABDAG8AbABvAHIAIABSAGUAZAAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAcwBjAHIAaQBwAHQAOgBnAHIAYQBuAGQARQByAHIAbwByAHMAKwArAAoAIAAgACAAIAAgACAAIAAgAH0ACgAgACAAIAAgACAAIAAgACAAJABjAG8AdQBuAHQAKwArAAoAIAAgACAAIAB9AAoAfQAKAAoAZgBvAHIAZQBhAGMAaAAgACgAJABnAHIAbwB1AHAAIABpAG4AIAAkAGcAcgBvAHUAcABzACkAIAB7AAoAIAAgACAAIAAkAGYAbwBsAGQAZQByAFYAaQBkAGUAbwBGAGkAbABlAHMAIAA9ACAAQAAoACQAZwByAG8AdQBwAC4ARwByAG8AdQBwACAAfAAgAFcAaABlAHIAZQAtAE8AYgBqAGUAYwB0ACAAewAgACQAdgBpAGQAZQBvAEUAeAB0AHMAIAAtAGMAbwBuAHQAYQBpAG4AcwAgACQAXwAuAEUAeAB0AGUAbgBzAGkAbwBuAC4AVABvAEwAbwB3AGUAcgAoACkAIAB9ACAAfAAgAFMAbwByAHQALQBPAGIAagBlAGMAdAAgAEUAYQByAGwAaQBlAHMAdABUAGkAbQBlACkACgAgACAAIAAgACQAZgBvAGwAZABlAHIAUABkAGYARgBpAGwAZQBzACAAIAAgAD0AIABAACgAJABnAHIAbwB1AHAALgBHAHIAbwB1AHAAIAB8ACAAVwBoAGUAcgBlAC0ATwBiAGoAZQBjAHQAIAB7ACAAJABwAGQAZgBFAHgAdABzACAALQBjAG8AbgB0AGEAaQBuAHMAIAAkAF8ALgBFAHgAdABlAG4AcwBpAG8AbgAuAFQAbwBMAG8AdwBlAHIAKAApACAAfQAgACAAIAB8ACAAUwBvAHIAdAAtAE8AYgBqAGUAYwB0ACAARQBhAHIAbABpAGUAcwB0AFQAaQBtAGUAKQAKAAoAIAAgACAAIAAkAHYAVABvAHQAYQBsACAAPQAgACQAZgBvAGwAZABlAHIAVgBpAGQAZQBvAEYAaQBsAGUAcwAuAEMAbwB1AG4AdAAKACAAIAAgACAAJABwAFQAbwB0AGEAbAAgAD0AIAAkAGYAbwBsAGQAZQByAFAAZABmAEYAaQBsAGUAcwAuAEMAbwB1AG4AdAAKAAoAIAAgACAAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtACIACgAgACAAIAAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAFsARgBPAEwARABFAFIAXQAgACAAJAAoACQAZwByAG8AdQBwAC4ATgBhAG0AZQApACIAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAATQBhAGcAZQBuAHQAYQAKACAAIAAgACAACgAgACAAIAAgACQAaQBuAGYAbwBQAGEAcgB0AHMAIAA9ACAAQAAoACkACgAgACAAIAAgAGkAZgAgACgAJAB2AFQAbwB0AGEAbAAgAC0AZwB0ACAAMAApACAAewAKACAAIAAgACAAIAAgACAAIAAkAHYARABpAGcAaQB0AHMAIAA9ACAAaQBmACAAKAAkAHYAVABvAHQAYQBsACAALQBsAHQAIAAxADAAMAApACAAewAgADIAIAB9ACAAZQBsAHMAZQAgAHsAIAAkAHYAVABvAHQAYQBsAC4AVABvAFMAdAByAGkAbgBnACgAKQAuAEwAZQBuAGcAdABoACAAfQAKACAAIAAgACAAIAAgACAAIAAkAGkAbgBmAG8AUABhAHIAdABzACAAKwA9ACAAIgAkAHYAVABvAHQAYQBsACAAVgBpAGQAZQBvACAAZgBpAGwAZQAoAHMAKQAgAC0ALQAgAHUAcwBpAG4AZwAgACQAdgBEAGkAZwBpAHQAcwAtAGQAaQBnAGkAdAAgAG4AdQBtAGIAZQByAGkAbgBnACIACgAgACAAIAAgAH0ACgAgACAAIAAgAGkAZgAgACgAJABwAFQAbwB0AGEAbAAgAC0AZwB0ACAAMAApACAAewAKACAAIAAgACAAIAAgACAAIAAkAHAARABpAGcAaQB0AHMAIAA9ACAAaQBmACAAKAAkAHAAVABvAHQAYQBsACAALQBsAHQAIAAxADAAMAApACAAewAgADIAIAB9ACAAZQBsAHMAZQAgAHsAIAAkAHAAVABvAHQAYQBsAC4AVABvAFMAdAByAGkAbgBnACgAKQAuAEwAZQBuAGcAdABoACAAfQAKACAAIAAgACAAIAAgACAAIAAkAGkAbgBmAG8AUABhAHIAdABzACAAKwA9ACAAIgAkAHAAVABvAHQAYQBsACAAUABEAEYAIABmAGkAbABlACgAcwApACAALQAtACAAdQBzAGkAbgBnACAAJABwAEQAaQBnAGkAdABzAC0AZABpAGcAaQB0ACAAbgB1AG0AYgBlAHIAaQBuAGcAIgAKACAAIAAgACAAfQAKACAAIAAgACAAJABpAG4AZgBvAEwAaQBuAGUAIAA9ACAAJABpAG4AZgBvAFAAYQByAHQAcwAgAC0AagBvAGkAbgAgACIAIAB8ACAAIgAKACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAgACIAIAAgACAAIAAgACAAIAAgACAAIAAkAGkAbgBmAG8ATABpAG4AZQAiACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAEQAYQByAGsATQBhAGcAZQBuAHQAYQAKAAoAIAAgACAAIABpAGYAIAAoACQAdgBUAG8AdABhAGwAIAAtAGcAdAAgADAAKQAgAHsACgAgACAAIAAgACAAIAAgACAAJAB2AEQAaQBnAGkAdABzACAAPQAgAGkAZgAgACgAJAB2AFQAbwB0AGEAbAAgAC0AbAB0ACAAMQAwADAAKQAgAHsAIAAyACAAfQAgAGUAbABzAGUAIAB7ACAAJAB2AFQAbwB0AGEAbAAuAFQAbwBTAHQAcgBpAG4AZwAoACkALgBMAGUAbgBnAHQAaAAgAH0ACgAgACAAIAAgACAAIAAgACAAJgAgACQAcAByAG8AYwBlAHMAcwBGAGkAbABlAHMAIAAkAGYAbwBsAGQAZQByAFYAaQBkAGUAbwBGAGkAbABlAHMAIAAkAHYARABpAGcAaQB0AHMACgAgACAAIAAgAH0ACgAgACAAIAAgAGkAZgAgACgAJABwAFQAbwB0AGEAbAAgAC0AZwB0ACAAMAApACAAewAKACAAIAAgACAAIAAgACAAIAAkAHAARABpAGcAaQB0AHMAIAA9ACAAaQBmACAAKAAkAHAAVABvAHQAYQBsACAALQBsAHQAIAAxADAAMAApACAAewAgADIAIAB9ACAAZQBsAHMAZQAgAHsAIAAkAHAAVABvAHQAYQBsAC4AVABvAFMAdAByAGkAbgBnACgAKQAuAEwAZQBuAGcAdABoACAAfQAKACAAIAAgACAAIAAgACAAIAAmACAAJABwAHIAbwBjAGUAcwBzAEYAaQBsAGUAcwAgACQAZgBvAGwAZABlAHIAUABkAGYARgBpAGwAZQBzACAAJABwAEQAaQBnAGkAdABzAAoAIAAgACAAIAB9AAoAfQAKAAoAVwByAGkAdABlAC0ASABvAHMAdAAgACIAIgAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0AIgAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAFsAUwBVAE0ATQBBAFIAWQBdACAAVABvAHQAYQBsACAAbQBhAHQAYwBoAGUAZAAgADoAIAAkAHQAbwB0AGEAbAAiACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAEcAcgBlAGUAbgAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAFsAUwBVAE0ATQBBAFIAWQBdACAARgBvAGwAZABlAHIAcwAgACAAIAAgACAAIAAgADoAIAAkACgAJABnAHIAbwB1AHAAcwAuAEMAbwB1AG4AdAApACIAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAARwByAGUAZQBuAAoAVwByAGkAdABlAC0ASABvAHMAdAAgACIAWwBTAFUATQBNAEEAUgBZAF0AIABSAGUAbgBhAG0AZQBkACAAIAAgACAAIAAgACAAOgAgACQAcwBjAHIAaQBwAHQAOgBnAHIAYQBuAGQAUgBlAG4AYQBtAGUAZAAiACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAEcAcgBlAGUAbgAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAFsAUwBVAE0ATQBBAFIAWQBdACAAUwBrAGkAcABwAGUAZAAgACAAIAAgACAAIAAgADoAIAAkAHMAYwByAGkAcAB0ADoAZwByAGEAbgBkAFMAawBpAHAAcABlAGQAIgAgAC0ARgBvAHIAZQBnAHIAbwB1AG4AZABDAG8AbABvAHIAIABHAHIAZQBlAG4ACgBXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgBbAFMAVQBNAE0AQQBSAFkAXQAgAEUAcgByAG8AcgBzACAAIAAgACAAIAAgACAAIAA6ACAAJABzAGMAcgBpAHAAdAA6AGcAcgBhAG4AZABFAHIAcgBvAHIAcwAiACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAEcAcgBlAGUAbgAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAFsAUwBVAEMAQwBFAFMAUwBdACAATgB1AG0AYgBlAHIAaQBuAGcAIAB0AGEAcwBrACAAYwBvAG0AcABsAGUAdABlACEAIgAgAC0ARgBvAHIAZQBnAHIAbwB1AG4AZABDAG8AbABvAHIAIABHAHIAZQBlAG4ACgBXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgAiAAoAVwByAGkAdABlAC0ASABvAHMAdAAgACIAUAByAGUAcwBzACAAYQBuAHkAIABrAGUAeQAgAHQAbwAgAGUAeABpAHQALgAuAC4AIgAKAFsAdgBvAGkAZABdAFsAUwB5AHMAdABlAG0ALgBDAG8AbgBzAG8AbABlAF0AOgA6AFIAZQBhAGQASwBlAHkAKAAkAHQAcgB1AGUAKQA="

echo -------------------------------------------------------------------------------------------------------
echo =======================================================================================================
echo [FINISHED] Script execution finished. GitHub: https://github.com/Biraj2004
echo =======================================================================================================
echo.
pause
endlocal
