@echo off
setlocal EnableDelayedExpansion
title Strip Numbered Prefix - by Biraj2004
cd /d "%~dp0"

:: =======================================================================================================
:: GitHub      : https://github.com/Biraj2004
:: Developer   : Biraj
:: Description : Recursively scans this folder and ALL subfolders for
::                .mp4, .mkv, .webm, and .pdf files, and strips a leading numeric
::                prefix (e.g. "07-", "12 -") from each filename, IF
::                the text before the FIRST hyphen is made up of
::                digits only.
::                - Only the part up to and including the first "-"
::                  is removed. Everything after it is left untouched.
::                - Files whose prefix is NOT purely numeric (e.g.
::                  "Part1-Intro.mp4") are left alone.
::                - Files with no hyphen at all are left alone.
::                - Re-running this script is SAFE: files without a numeric
::                  prefix are skipped automatically.
:: =======================================================================================================

echo =======================================================================================================
echo                       STRIP NUMBERED PREFIX SCRIPT
echo                       Developed by : Biraj
echo                       GitHub       : https://github.com/Biraj2004
echo =======================================================================================================
echo.
echo [INFO] Working Folder   : %CD%
echo [INFO] Target Extensions: .mp4, .mkv, .webm, .pdf
echo [INFO] Action           : Strip leading "NUMBER-" prefix from filenames
echo [INFO] Scope            : Current folder + ALL subfolders (Recursive)
echo [INFO] Safety           : Only files with a PURELY NUMERIC prefix before
echo [INFO]                    the first hyphen are touched. Everything else
echo [INFO]                    is left completely untouched.
echo.
echo =======================================================================================================
echo  WARNING: This will RENAME .mp4, .mkv, .webm, and .pdf files inside:
echo    %CD%
echo  ...and every SUB-FOLDER inside it.
echo =======================================================================================================
echo.
set "CONFIRM="
set /p CONFIRM=Type Y and press Enter to proceed, or N to cancel : 

if /i "%CONFIRM%"=="Y" goto :PROCEED
if /i "%CONFIRM%"=="YES" goto :PROCEED

echo.
echo [CANCELLED] No files were scanned or renamed. Exiting safely.
echo.
pause
endlocal
exit /b 0

:PROCEED
echo.
echo [PROCESSING] Launching PowerShell engine...
echo =======================================================================================================

where powershell >nul 2>&1
if errorlevel 1 (
    echo [ERROR] PowerShell was not found on this system. Cannot continue.
    echo.
    pause
    exit /b 1
)

powershell -NoProfile -NoLogo -ExecutionPolicy Bypass -EncodedCommand "JABFAHIAcgBvAHIAQQBjAHQAaQBvAG4AUAByAGUAZgBlAHIAZQBuAGMAZQAgAD0AIAAnAFMAdABvAHAAJwAKACQAZQB4AHQAcwAgAD0AIABAACgAJwAuAG0AcAA0ACcALAAnAC4AbQBrAHYAJwAsACcALgB3AGUAYgBtACcALAAnAC4AcABkAGYAJwApAAoAJAByAG8AbwB0ACAAPQAgAEcAZQB0AC0ATABvAGMAYQB0AGkAbwBuAAoAVwByAGkAdABlAC0ASABvAHMAdAAgACIAWwBJAE4ARgBPAF0AIABTAGMAYQBuAG4AaQBuAGcAIABmAG8AbABkAGUAcgAgACgAcgBlAGMAdQByAHMAaQB2AGUAKQA6ACAAJAByAG8AbwB0ACIAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAARwByAGEAeQAKAAoAJABwAGEAdAB0AGUAcgBuACAAPQAgACcAXgBcAGQAKwBcAHMAKgAtAFwAcwAqACcACgAkAGYAaQBsAGUAcwAgAD0AIABHAGUAdAAtAEMAaABpAGwAZABJAHQAZQBtACAALQBQAGEAdABoACAAJAByAG8AbwB0ACAALQBSAGUAYwB1AHIAcwBlACAALQBGAGkAbABlACAAfAAgAFcAaABlAHIAZQAtAE8AYgBqAGUAYwB0ACAAewAgAAoAIAAgACAAIAAoACQAZQB4AHQAcwAgAC0AYwBvAG4AdABhAGkAbgBzACAAJABfAC4ARQB4AHQAZQBuAHMAaQBvAG4ALgBUAG8ATABvAHcAZQByACgAKQApACAALQBhAG4AZAAgACgAJABfAC4ATgBhAG0AZQAgAC0AbQBhAHQAYwBoACAAJABwAGEAdAB0AGUAcgBuACkACgB9AAoAJAB0AG8AdABhAGwAIAA9ACAAJABmAGkAbABlAHMALgBDAG8AdQBuAHQACgAKAGkAZgAgACgAJAB0AG8AdABhAGwAIAAtAGUAcQAgADAAKQAgAHsACgAgACAAIAAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAFsASQBOAEYATwBdACAATgBvACAAbQBhAHQAYwBoAGkAbgBnACAAZgBpAGwAZQBzACAAKAAuAG0AcAA0ACwAIAAuAG0AawB2ACwAIAAuAHcAZQBiAG0ALAAgAC4AcABkAGYAKQAgAHcAaQB0AGgAIABuAHUAbQBlAHIAaQBjACAAcAByAGUAZgBpAHgAZQBzACAAZgBvAHUAbgBkAC4AIgAgAC0ARgBvAHIAZQBnAHIAbwB1AG4AZABDAG8AbABvAHIAIABZAGUAbABsAG8AdwAKACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAgACIAIgAKACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAgACIAUAByAGUAcwBzACAAYQBuAHkAIABrAGUAeQAgAHQAbwAgAGUAeABpAHQALgAuAC4AIgAKACAAIAAgACAAWwB2AG8AaQBkAF0AWwBTAHkAcwB0AGUAbQAuAEMAbwBuAHMAbwBsAGUAXQA6ADoAUgBlAGEAZABLAGUAeQAoACQAdAByAHUAZQApAAoAIAAgACAAIABlAHgAaQB0AAoAfQAKAAoAJABnAHIAbwB1AHAAcwAgAD0AIAAkAGYAaQBsAGUAcwAgAHwAIABHAHIAbwB1AHAALQBPAGIAagBlAGMAdAAgAEQAaQByAGUAYwB0AG8AcgB5AE4AYQBtAGUAIAB8ACAAUwBvAHIAdAAtAE8AYgBqAGUAYwB0ACAATgBhAG0AZQAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAFsASQBOAEYATwBdACAARgBvAHUAbgBkACAAJAB0AG8AdABhAGwAIABtAGEAdABjAGgAaQBuAGcAIABmAGkAbABlACgAcwApACAAYQBjAHIAbwBzAHMAIAAkACgAJABnAHIAbwB1AHAAcwAuAEMAbwB1AG4AdAApACAAZgBvAGwAZABlAHIAKABzACkALgAiACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAEcAcgBhAHkACgBXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgAiAAoACgAkAHMAYwByAGkAcAB0ADoAZwByAGEAbgBkAFIAZQBuAGEAbQBlAGQAIAA9ACAAMAAKACQAcwBjAHIAaQBwAHQAOgBnAHIAYQBuAGQAUwBrAGkAcABwAGUAZAAgAD0AIAAwAAoAJABzAGMAcgBpAHAAdAA6AGcAcgBhAG4AZABFAHIAcgBvAHIAcwAgACAAPQAgADAACgAKAGYAbwByAGUAYQBjAGgAIAAoACQAZwByAG8AdQBwACAAaQBuACAAJABnAHIAbwB1AHAAcwApACAAewAKACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAgACIALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAiAAoAIAAgACAAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgBbAEYATwBMAEQARQBSAF0AIAAgACQAKAAkAGcAcgBvAHUAcAAuAE4AYQBtAGUAKQAiACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAE0AYQBnAGUAbgB0AGEACgAgACAAIAAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiACAAIAAgACAAIAAgACAAIAAgACAAJAAoACQAZwByAG8AdQBwAC4AQwBvAHUAbgB0ACkAIABmAGkAbABlACgAcwApACAAdwBpAHQAaAAgAG4AdQBtAGUAcgBpAGMAIABwAHIAZQBmAGkAeABlAHMAIgAgAC0ARgBvAHIAZQBnAHIAbwB1AG4AZABDAG8AbABvAHIAIABEAGEAcgBrAE0AYQBnAGUAbgB0AGEACgAKACAAIAAgACAAZgBvAHIAZQBhAGMAaAAgACgAJABmAGkAbABlACAAaQBuACAAJABnAHIAbwB1AHAALgBHAHIAbwB1AHAAKQAgAHsACgAgACAAIAAgACAAIAAgACAAJABuAGUAdwBOAGEAbQBlACAAPQAgACQAZgBpAGwAZQAuAE4AYQBtAGUAIAAtAHIAZQBwAGwAYQBjAGUAIAAnAF4AXABkACsAXABzACoALQBcAHMAKgAnACwAJwAnAAoAIAAgACAAIAAgACAAIAAgAGkAZgAgACgAJABmAGkAbABlAC4ATgBhAG0AZQAgAC0AZQBxACAAJABuAGUAdwBOAGEAbQBlACkAIAB7AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAgACIAWwBTAEsASQBQAF0AIAAgACAAIAAgACQAKAAkAGYAaQBsAGUALgBOAGEAbQBlACkAIAAgACgAcAByAGUAZgBpAHgAIABhAGwAcgBlAGEAZAB5ACAAYQBiAHMAZQBuAHQAKQAiACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAEQAYQByAGsARwByAGEAeQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAcwBjAHIAaQBwAHQAOgBnAHIAYQBuAGQAUwBrAGkAcABwAGUAZAArACsACgAgACAAIAAgACAAIAAgACAAIAAgACAAIABjAG8AbgB0AGkAbgB1AGUACgAgACAAIAAgACAAIAAgACAAfQAKAAoAIAAgACAAIAAgACAAIAAgAHQAcgB5ACAAewAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAFIAZQBuAGEAbQBlAC0ASQB0AGUAbQAgAC0ATABpAHQAZQByAGEAbABQAGEAdABoACAAJABmAGkAbABlAC4ARgB1AGwAbABOAGEAbQBlACAALQBOAGUAdwBOAGEAbQBlACAAJABuAGUAdwBOAGEAbQBlACAALQBFAHIAcgBvAHIAQQBjAHQAaQBvAG4AIABTAHQAbwBwAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAgACIAWwBSAEUATgBBAE0ARQBEAF0AIAAgACQAKAAkAGYAaQBsAGUALgBOAGEAbQBlACkAIgAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiACAAIAAgACAAIAAtAC0APgAgACAAIAAkAG4AZQB3AE4AYQBtAGUAIgAgAC0ARgBvAHIAZQBnAHIAbwB1AG4AZABDAG8AbABvAHIAIABDAHkAYQBuAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABzAGMAcgBpAHAAdAA6AGcAcgBhAG4AZABSAGUAbgBhAG0AZQBkACsAKwAKACAAIAAgACAAIAAgACAAIAB9ACAAYwBhAHQAYwBoACAAewAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAFsARQBSAFIATwBSAF0AIAAgACAAIABDAG8AdQBsAGQAIABuAG8AdAAgAHIAZQBuAGEAbQBlACAAJAAoACQAZgBpAGwAZQAuAEYAdQBsAGwATgBhAG0AZQApACAALQAtACAAJAAoACQAXwAuAEUAeABjAGUAcAB0AGkAbwBuAC4ATQBlAHMAcwBhAGcAZQApACIAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAAUgBlAGQACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAHMAYwByAGkAcAB0ADoAZwByAGEAbgBkAEUAcgByAG8AcgBzACsAKwAKACAAIAAgACAAIAAgACAAIAB9AAoAIAAgACAAIAB9AAoAfQAKAAoAVwByAGkAdABlAC0ASABvAHMAdAAgACIAIgAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0AIgAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAFsAUwBVAE0ATQBBAFIAWQBdACAAVABvAHQAYQBsACAAbQBhAHQAYwBoAGUAZAAgADoAIAAkAHQAbwB0AGEAbAAiACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAEcAcgBlAGUAbgAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAFsAUwBVAE0ATQBBAFIAWQBdACAARgBvAGwAZABlAHIAcwAgACAAIAAgACAAIAAgADoAIAAkACgAJABnAHIAbwB1AHAAcwAuAEMAbwB1AG4AdAApACIAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAARwByAGUAZQBuAAoAVwByAGkAdABlAC0ASABvAHMAdAAgACIAWwBTAFUATQBNAEEAUgBZAF0AIABSAGUAbgBhAG0AZQBkACAAIAAgACAAIAAgACAAOgAgACQAcwBjAHIAaQBwAHQAOgBnAHIAYQBuAGQAUgBlAG4AYQBtAGUAZAAiACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAEcAcgBlAGUAbgAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAFsAUwBVAE0ATQBBAFIAWQBdACAAUwBrAGkAcABwAGUAZAAgACAAIAAgACAAIAAgADoAIAAkAHMAYwByAGkAcAB0ADoAZwByAGEAbgBkAFMAawBpAHAAcABlAGQAIgAgAC0ARgBvAHIAZQBnAHIAbwB1AG4AZABDAG8AbABvAHIAIABHAHIAZQBlAG4ACgBXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgBbAFMAVQBNAE0AQQBSAFkAXQAgAEUAcgByAG8AcgBzACAAIAAgACAAIAAgACAAIAA6ACAAJABzAGMAcgBpAHAAdAA6AGcAcgBhAG4AZABFAHIAcgBvAHIAcwAiACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAEcAcgBlAGUAbgAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAFsAUwBVAEMAQwBFAFMAUwBdACAAUwB0AHIAaQBwACAAbgB1AG0AZQByAGkAYwAgAHAAcgBlAGYAaQB4ACAAdABhAHMAawAgAGMAbwBtAHAAbABlAHQAZQAhACIAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAARwByAGUAZQBuAAoAVwByAGkAdABlAC0ASABvAHMAdAAgACIAIgAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAFAAcgBlAHMAcwAgAGEAbgB5ACAAawBlAHkAIAB0AG8AIABlAHgAaQB0AC4ALgAuACIACgBbAHYAbwBpAGQAXQBbAFMAeQBzAHQAZQBtAC4AQwBvAG4AcwBvAGwAZQBdADoAOgBSAGUAYQBkAEsAZQB5ACgAJAB0AHIAdQBlACkA"

echo -------------------------------------------------------------------------------------------------------
echo =======================================================================================================
echo [FINISHED] Script execution finished. GitHub: https://github.com/Biraj2004
echo =======================================================================================================
echo.
pause
endlocal
