@echo off
setlocal EnableDelayedExpansion
title Remove @hamaracollege Watermark - by Biraj2004
cd /d "%~dp0"

:: =======================================================================================================
:: GitHub      : https://github.com/Biraj2004
:: Developer   : Biraj
:: Description : Recursively scans this folder and ALL subfolders for
::                ANY file whose name contains the "@hamaracollege" /
::                "@hmaracollege" watermark tag (in common case
::                variations), and strips ONLY that tag out of the
::                filename.
::                - Works on ALL file types (mp4, srt, vtt, pdf, etc.)
::                  since Udemy course downloads mix file types.
::                - Nothing else in the filename is touched.
::                - Re-running this script is SAFE: files without the
::                  watermark tag are skipped automatically.
:: =======================================================================================================

echo =======================================================================================================
echo                       REMOVE "@HAMARACOLLEGE" WATERMARK SCRIPT
echo                       Developed by : Biraj
echo                       GitHub       : https://github.com/Biraj2004
echo =======================================================================================================
echo.
echo [INFO] Working Folder   : %CD%
echo [INFO] Target Files     : ALL files (any extension)
echo [INFO] Text Removed     : "@hamaracollege" / "@hmaracollege" (common case variants)
echo [INFO] Scope            : Current folder + ALL subfolders (Recursive)
echo [INFO] Safety           : Only the matched tag text is stripped out.
echo [INFO]                    The rest of each filename is left untouched.
echo.
echo =======================================================================================================
echo  WARNING: This will RENAME files containing "@hamaracollege" inside:
echo    %CD%
echo  ...and every SUB-FOLDER inside it.
echo =======================================================================================================
echo.
set "CONFIRM="
set /p CONFIRM=Type Y and press Enter to proceed, or N to cancel : 

if /i "%CONFIRM%"=="Y" goto :PROCEED
if /i "%CONFIRM%"=="YES" goto :PROCEED

echo.
echo [CANCELLED] No files were scanned or renamed. Exiting safely.
echo.
pause
endlocal
exit /b 0

:PROCEED
echo.
echo [PROCESSING] Launching PowerShell engine...
echo =======================================================================================================

where powershell >nul 2>&1
if errorlevel 1 (
    echo [ERROR] PowerShell was not found on this system. Cannot continue.
    echo.
    pause
    exit /b 1
)

powershell -NoProfile -NoLogo -ExecutionPolicy Bypass -EncodedCommand "JABFAHIAcgBvAHIAQQBjAHQAaQBvAG4AUAByAGUAZgBlAHIAZQBuAGMAZQAgAD0AIAAnAFMAdABvAHAAJwAKACQAcgBvAG8AdAAgAD0AIABHAGUAdAAtAEwAbwBjAGEAdABpAG8AbgAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAFsASQBOAEYATwBdACAAUwBjAGEAbgBuAGkAbgBnACAAZgBvAGwAZABlAHIAIAAoAHIAZQBjAHUAcgBzAGkAdgBlACkAOgAgACQAcgBvAG8AdAAiACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAEcAcgBhAHkACgAKACQAcABhAHQAdABlAHIAbgAgAD0AIAAnACgAPwBpACkAQABoAFsAYQBdAD8AbQBhAHIAYQBjAG8AbABsAGUAZwBlACcACgAkAGYAaQBsAGUAcwAgAD0AIABHAGUAdAAtAEMAaABpAGwAZABJAHQAZQBtACAALQBQAGEAdABoACAAJAByAG8AbwB0ACAALQBSAGUAYwB1AHIAcwBlACAALQBGAGkAbABlACAAfAAgAFcAaABlAHIAZQAtAE8AYgBqAGUAYwB0ACAAewAgACQAXwAuAE4AYQBtAGUAIAAtAG0AYQB0AGMAaAAgACQAcABhAHQAdABlAHIAbgAgAH0ACgAkAHQAbwB0AGEAbAAgAD0AIAAkAGYAaQBsAGUAcwAuAEMAbwB1AG4AdAAKAAoAaQBmACAAKAAkAHQAbwB0AGEAbAAgAC0AZQBxACAAMAApACAAewAKACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAgACIAWwBJAE4ARgBPAF0AIABOAG8AIABtAGEAdABjAGgAaQBuAGcAIABmAGkAbABlAHMAIAB3AGkAdABoACAAdwBhAHQAZQByAG0AYQByAGsAIAAoAEAAaABhAG0AYQByAGEAYwBvAGwAbABlAGcAZQAgAC8AIABAAGgAbQBhAHIAYQBjAG8AbABsAGUAZwBlACkAIABmAG8AdQBuAGQALgAiACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAFkAZQBsAGwAbwB3AAoAIAAgACAAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgAiAAoAIAAgACAAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgBQAHIAZQBzAHMAIABhAG4AeQAgAGsAZQB5ACAAdABvACAAZQB4AGkAdAAuAC4ALgAiAAoAIAAgACAAIABbAHYAbwBpAGQAXQBbAFMAeQBzAHQAZQBtAC4AQwBvAG4AcwBvAGwAZQBdADoAOgBSAGUAYQBkAEsAZQB5ACgAJAB0AHIAdQBlACkACgAgACAAIAAgAGUAeABpAHQACgB9AAoACgAkAGcAcgBvAHUAcABzACAAPQAgACQAZgBpAGwAZQBzACAAfAAgAEcAcgBvAHUAcAAtAE8AYgBqAGUAYwB0ACAARABpAHIAZQBjAHQAbwByAHkATgBhAG0AZQAgAHwAIABTAG8AcgB0AC0ATwBiAGoAZQBjAHQAIABOAGEAbQBlAAoAVwByAGkAdABlAC0ASABvAHMAdAAgACIAWwBJAE4ARgBPAF0AIABGAG8AdQBuAGQAIAAkAHQAbwB0AGEAbAAgAG0AYQB0AGMAaABpAG4AZwAgAGYAaQBsAGUAKABzACkAIABhAGMAcgBvAHMAcwAgACQAKAAkAGcAcgBvAHUAcABzAC4AQwBvAHUAbgB0ACkAIABmAG8AbABkAGUAcgAoAHMAKQAuACIAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAARwByAGEAeQAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiACIACgAKACQAcwBjAHIAaQBwAHQAOgBnAHIAYQBuAGQAUgBlAG4AYQBtAGUAZAAgAD0AIAAwAAoAJABzAGMAcgBpAHAAdAA6AGcAcgBhAG4AZABTAGsAaQBwAHAAZQBkACAAPQAgADAACgAkAHMAYwByAGkAcAB0ADoAZwByAGEAbgBkAEUAcgByAG8AcgBzACAAIAA9ACAAMAAKAAoAZgBvAHIAZQBhAGMAaAAgACgAJABnAHIAbwB1AHAAIABpAG4AIAAkAGcAcgBvAHUAcABzACkAIAB7AAoAIAAgACAAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtACIACgAgACAAIAAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAFsARgBPAEwARABFAFIAXQAgACAAJAAoACQAZwByAG8AdQBwAC4ATgBhAG0AZQApACIAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAATQBhAGcAZQBuAHQAYQAKACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAgACIAIAAgACAAIAAgACAAIAAgACAAIAAkACgAJABnAHIAbwB1AHAALgBDAG8AdQBuAHQAKQAgAGYAaQBsAGUAKABzACkAIABtAGEAdABjAGgAaQBuAGcAIAB3AGEAdABlAHIAbQBhAHIAawAiACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAEQAYQByAGsATQBhAGcAZQBuAHQAYQAKAAoAIAAgACAAIABmAG8AcgBlAGEAYwBoACAAKAAkAGYAaQBsAGUAIABpAG4AIAAkAGcAcgBvAHUAcAAuAEcAcgBvAHUAcAApACAAewAKACAAIAAgACAAIAAgACAAIAAkAG4AZQB3AE4AYQBtAGUAIAA9ACAAJABmAGkAbABlAC4ATgBhAG0AZQAgAC0AcgBlAHAAbABhAGMAZQAgACcAKAA/AGkAKQBAAGgAWwBhAF0APwBtAGEAcgBhAGMAbwBsAGwAZQBnAGUAJwAsACcAJwAKACAAIAAgACAAIAAgACAAIABpAGYAIAAoACQAZgBpAGwAZQAuAE4AYQBtAGUAIAAtAGUAcQAgACQAbgBlAHcATgBhAG0AZQApACAAewAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAFsAUwBLAEkAUABdACAAIAAgACAAIAAkACgAJABmAGkAbABlAC4ATgBhAG0AZQApACAAIAAoAHcAYQB0AGUAcgBtAGEAcgBrACAAdABhAGcAIABhAGwAcgBlAGEAZAB5ACAAYQBiAHMAZQBuAHQAKQAiACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAEQAYQByAGsARwByAGEAeQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAcwBjAHIAaQBwAHQAOgBnAHIAYQBuAGQAUwBrAGkAcABwAGUAZAArACsACgAgACAAIAAgACAAIAAgACAAIAAgACAAIABjAG8AbgB0AGkAbgB1AGUACgAgACAAIAAgACAAIAAgACAAfQAKAAoAIAAgACAAIAAgACAAIAAgAHQAcgB5ACAAewAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAFIAZQBuAGEAbQBlAC0ASQB0AGUAbQAgAC0ATABpAHQAZQByAGEAbABQAGEAdABoACAAJABmAGkAbABlAC4ARgB1AGwAbABOAGEAbQBlACAALQBOAGUAdwBOAGEAbQBlACAAJABuAGUAdwBOAGEAbQBlACAALQBFAHIAcgBvAHIAQQBjAHQAaQBvAG4AIABTAHQAbwBwAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAgACIAWwBSAEUATgBBAE0ARQBEAF0AIAAgACQAKAAkAGYAaQBsAGUALgBOAGEAbQBlACkAIgAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiACAAIAAgACAAIAAtAC0APgAgACAAIAAkAG4AZQB3AE4AYQBtAGUAIgAgAC0ARgBvAHIAZQBnAHIAbwB1AG4AZABDAG8AbABvAHIAIABDAHkAYQBuAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABzAGMAcgBpAHAAdAA6AGcAcgBhAG4AZABSAGUAbgBhAG0AZQBkACsAKwAKACAAIAAgACAAIAAgACAAIAB9ACAAYwBhAHQAYwBoACAAewAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAFsARQBSAFIATwBSAF0AIAAgACAAIABDAG8AdQBsAGQAIABuAG8AdAAgAHIAZQBuAGEAbQBlACAAJAAoACQAZgBpAGwAZQAuAEYAdQBsAGwATgBhAG0AZQApACAALQAtACAAJAAoACQAXwAuAEUAeABjAGUAcAB0AGkAbwBuAC4ATQBlAHMAcwBhAGcAZQApACIAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAAUgBlAGQACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAHMAYwByAGkAcAB0ADoAZwByAGEAbgBkAEUAcgByAG8AcgBzACsAKwAKACAAIAAgACAAIAAgACAAIAB9AAoAIAAgACAAIAB9AAoAfQAKAAoAVwByAGkAdABlAC0ASABvAHMAdAAgACIAIgAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0ALQAtAC0AIgAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAFsAUwBVAE0ATQBBAFIAWQBdACAAVABvAHQAYQBsACAAbQBhAHQAYwBoAGUAZAAgADoAIAAkAHQAbwB0AGEAbAAiACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAEcAcgBlAGUAbgAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAFsAUwBVAE0ATQBBAFIAWQBdACAARgBvAGwAZABlAHIAcwAgACAAIAAgACAAIAAgADoAIAAkACgAJABnAHIAbwB1AHAAcwAuAEMAbwB1AG4AdAApACIAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAARwByAGUAZQBuAAoAVwByAGkAdABlAC0ASABvAHMAdAAgACIAWwBTAFUATQBNAEEAUgBZAF0AIABSAGUAbgBhAG0AZQBkACAAIAAgACAAIAAgACAAOgAgACQAcwBjAHIAaQBwAHQAOgBnAHIAYQBuAGQAUgBlAG4AYQBtAGUAZAAiACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAEcAcgBlAGUAbgAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAFsAUwBVAE0ATQBBAFIAWQBdACAAUwBrAGkAcABwAGUAZAAgACAAIAAgACAAIAAgADoAIAAkAHMAYwByAGkAcAB0ADoAZwByAGEAbgBkAFMAawBpAHAAcABlAGQAIgAgAC0ARgBvAHIAZQBnAHIAbwB1AG4AZABDAG8AbABvAHIAIABHAHIAZQBlAG4ACgBXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgBbAFMAVQBNAE0AQQBSAFkAXQAgAEUAcgByAG8AcgBzACAAIAAgACAAIAAgACAAIAA6ACAAJABzAGMAcgBpAHAAdAA6AGcAcgBhAG4AZABFAHIAcgBvAHIAcwAiACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAEcAcgBlAGUAbgAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAFsAUwBVAEMAQwBFAFMAUwBdACAAVwBhAHQAZQByAG0AYQByAGsAIAByAGUAbQBvAHYAYQBsACAAdABhAHMAawAgAGMAbwBtAHAAbABlAHQAZQAhACIAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAARwByAGUAZQBuAAoAVwByAGkAdABlAC0ASABvAHMAdAAgACIAIgAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAFAAcgBlAHMAcwAgAGEAbgB5ACAAawBlAHkAIAB0AG8AIABlAHgAaQB0AC4ALgAuACIACgBbAHYAbwBpAGQAXQBbAFMAeQBzAHQAZQBtAC4AQwBvAG4AcwBvAGwAZQBdADoAOgBSAGUAYQBkAEsAZQB5ACgAJAB0AHIAdQBlACkA"

echo -------------------------------------------------------------------------------------------------------
echo =======================================================================================================
echo [FINISHED] Script execution finished. GitHub: https://github.com/Biraj2004
echo =======================================================================================================
echo.
pause
endlocal
